=== varga22/HK74CEXML/HK74CE_1015/HK74CE_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Saját típusok definiálása -->
    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}/\d{2}/(I|II)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ME"/>
            <xs:enumeration value="BME"/>
            <xs:enumeration value="ELTE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Hallgató elem definiálása -->
    <xs:element name="hallgato">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hnev" type="xs:string"/>
                <xs:element name="szulev" type="xs:positiveInteger"/>
                <xs:element name="szak">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="evf" type="xs:positiveInteger" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Időpont elem definiálása -->
    <xs:complexType name="idopontTipus">
        <xs:sequence>
            <xs:element name="nap" type="xs:string"/>
            <xs:element name="tol" type="xs:string"/>
            <xs:element name="ig" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Kurzus elem definiálása -->
    <xs:element name="kurzus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzusnev" type="xs:string"/>
                <xs:element name="kredit" type="xs:positiveInteger"/>
                <xs:element name="hely" type="xs:string"/>
                <xs:element name="idopont" type="idopontTipus"/>
                <xs:element name="oktato" type="xs:string"/>
                <xs:element name="oraado" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="idTipus" use="required"/>
            <xs:attribute name="jovahagyas" type="igenNemTipus"/>
            <xs:attribute name="nyelv" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Kurzusok elem definiálása -->
    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kurzus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Szabályok megadása az elemekre -->
    <xs:element name="Neptunkod_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                <xs:element ref="kurzusok"/>
            </xs:sequence>
            <xs:attribute name="tanev" type="tanevTipus" use="required"/>
            <xs:attribute name="egyetem" type="egyetemTipus" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== varga22/HK74CEXML/HK74CE_1015/HK74CE_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<Neptunkod_kurzusfelvetel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="HK74CE_kurzusfelvetel.xsd" tanev="2024/25/I" egyetem="ME">
    <hallgato>
        <hnev>Varga Bence</hnev>
        <szulev>2000</szulev>
        <szak evf="3">Programtervező Informatikus</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="HK74CE01" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Számítógép Hálózatok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXVII. előadó</hely>
            <idopont>
                <nap>Hétfő</nap>
                <tol>08:00</tol>
                <ig>09:30</ig>
            </idopont>
            <oktato>Dr. Kovács Szilveszter</oktato>
            <oraado>Gyakorlati oktató</oraado>
        </kurzus>
        <kurzus id="HK74CE02" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>103-as terem</hely>
            <idopont>
                <nap>Kedd</nap>
                <tol>10:00</tol>
                <ig>11:30</ig>
            </idopont>
            <oktato>Bednarik László</oktato>
            <oraado>Előadás oktató</oraado>
        </kurzus>
        <kurzus id="HK74CE03">
            <kurzusnev>Szoftvertechnológia</kurzusnev>
            <kredit>5</kredit>
            <hely>III. előadó</hely>
            <idopont>
                <nap>Szerda</nap>
                <tol>08:00</tol>
                <ig>10:00</ig>
            </idopont>
            <oktato>Dr. Mileff Péter</oktato>
        </kurzus>
        <kurzus id="HK74CE04">
            <kurzusnev>Vállalati Információs Rendszerek</kurzusnev>
            <kredit>5</kredit>
            <hely>103-as terem</hely>
            <idopont>
                <nap>Szerda</nap>
                <tol>14:00</tol>
                <ig>16:00</ig>
            </idopont>
            <oktato>Dr. Sasvári Péter</oktato>
        </kurzus>
        <kurzus id="HK74CE05">
            <kurzusnev>Mesterséges Intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII. előadó</hely>
            <idopont>
                <nap>Szerda</nap>
                <tol>16:00</tol>
                <ig>18:00</ig>
            </idopont>
            <oktato>Dr. Kunné Tamás Judit</oktato>
        </kurzus>
    </kurzusok>
</Neptunkod_kurzusfelvetel>
