<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE VB_orarend [
    <!ELEMENT VB_orarend (ora*)>
    <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
    <!ATTLIST ora id ID #REQUIRED>
    <!ATTLIST ora típus (előadás | gyakorlat) #REQUIRED>

    <!ELEMENT targy (#PCDATA)>
    <!ELEMENT idopont (nap, tol, ig)>
    <!ELEMENT nap (#PCDATA)>
    <!ELEMENT tol (#PCDATA)>
    <!ELEMENT ig (#PCDATA)>
    <!ELEMENT helyszin (#PCDATA)>
    <!ELEMENT oktato (#PCDATA)>
    <!ELEMENT szak (#PCDATA)>
]>

<VB_orarend>
    <ora id="id01" típus="előadás">
        <targy>Számítógép Hálózatok</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>08:00</tol>
            <ig>09:30</ig>
        </idopont>
        <helyszin>XXXVII. előadó</helyszin>
        <oktato>Dr. Kovács Szilveszter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    
    <ora id="id02" típus="előadás">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>103-es terem</helyszin>
        <oktato>Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    
    <ora id="id03" típus="gyakorlat">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>13:30</ig>
        </idopont>
        <helyszin>303-as terem</helyszin>
        <oktato>Dr. Farkas Gábor</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    
    <ora id="id04" típus="előadás">
        <targy>Szoftvertechnológia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>III. előadó</helyszin>
        <oktato>Dr. Mileff Péter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    
    <ora id="id05" típus="gyakorlat">
        <targy>Szoftvertechnológia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>III. előadó</helyszin>
        <oktato>Dr. Mileff Péter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="id06" típus="gyakorlat">
        <targy>Mesterséges Intelligencia alapok</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>X. előadó</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="id07" típus="előadás">
        <targy>Vállalati Információs rendszerek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>103. terem</helyszin>
        <oktato>Dr. Sasvári Péter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="id08" típus="előadás">
        <targy>Mesterésges Intelligencia alapok</targy>

        <idopont>
            <nap>Szerda</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>XXXII. előadó</helyszin>
        <oktato>Dr. Kunné Tamás Judit</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="id09" típus="gyakorlat">
        <targy>Vállalati információs rendszerek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>18:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>103. terem</helyszin>
        <oktato>Dr. Sasvári Péter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="id10" típus="gyakorlat">
        <targy>Számítógép Hálózatok</targy>
        <idopont>
            <nap>Csütörtök</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>III. előadó</helyszin>
        <oktato>Dr. Kovács Szilveszter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
</VB_orarend>