=== varga22/HK74CEXML/XMLTaskHK74CE/ElsőFeladat/XMLSchemaHK74CE.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- Összetett típus a névhez -->
    <xsd:complexType name="NevTipus">
        <xsd:sequence>
            <xsd:element name="Keresztnev" type="xsd:string"/>
            <xsd:element name="Vezeteknev" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Összetett típus a lakcímhez -->
    <xsd:complexType name="LakcimTipus">
        <xsd:sequence>
            <xsd:element name="Varos" type="xsd:string"/>
            <xsd:element name="Utca" type="xsd:string"/>
            <xsd:element name="Hazszam" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Összetett típus a kurzus típusához -->
    <xsd:complexType name="TipusTipus">
        <xsd:sequence>
            <xsd:element name="Eloadas" type="xsd:boolean"/>
            <xsd:element name="Gyakorlat" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Egyszerű típus a kredit értékéhez-->
    <xsd:simpleType name="KreditTipus">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Gyökérelem -->
    <xsd:element name="HK74CE_oktatas">
        <xsd:complexType>
            <xsd:sequence>
                <!-- Diákok -->
                <xsd:element name="Diakok">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Diak" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Nev" type="NevTipus"/>
                                        <xsd:element name="SzulDatum" type="xsd:date"/>
                                        <xsd:element name="Email" type="xsd:string" maxOccurs="unbounded"/>
                                        <xsd:element name="Lakcim" type="LakcimTipus"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="DiakID" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Tanárok -->
                <xsd:element name="Tanarok">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Tanar" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Nev" type="NevTipus"/>
                                        <xsd:element name="Beosztas" type="xsd:string"/>
                                        <xsd:element name="Szakterulet" type="xsd:string"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="TanarID" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Tantárgyak -->
                <xsd:element name="Tantargyak">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Tantargy" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Nev" type="xsd:string"/>
                                        <xsd:element name="Kredit" type="KreditTipus"/> <!-- Egyszerű típus -->
                                        <xsd:element name="Nyelv" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="TargyID" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Termek -->
                <xsd:element name="Termek">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Terem" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Nev" type="xsd:string"/>
                                        <xsd:element name="Kapacitas" type="xsd:integer"/>
                                        <xsd:element name="Felszereles" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="TeremID" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>


                <!-- Kurzusok -->
                <xsd:element name="Kurzusok">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Kurzus" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Idopont" type="xsd:date"/>
                                        <xsd:element name="Tipus" type="TipusTipus"/>
                                        <xsd:element name="Letszam" type="xsd:integer"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="KurzusID" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                    <!-- Egyedi kurzus ID (Nem lehet két azonos a kurzus kód) -->
                    <xsd:unique name="UniqueKurzusID">
                        <xsd:selector xpath="Kurzus"/>
                        <xsd:field xpath="@KurzusID"/>
                    </xsd:unique>
                </xsd:element>

                <!-- Kapcsolatok -->
                <xsd:element name="Kapcsolatok">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="DiakKurzusKapcsolatok">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Kapcsolat" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Vizsga" type="xsd:integer"/>
                                                    <xsd:element name="Alairas" type="xsd:string"/>
                                                </xsd:sequence>
                                                <xsd:attribute name="DiakID" type="xsd:string" use="required"/>
                                                <xsd:attribute name="KurzusID" type="xsd:string" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Kulcsok és referenciák -->
        <xsd:key name="DiakPrimaryKey">
            <xsd:selector xpath="Diakok/Diak"/>
            <xsd:field xpath="@DiakID"/>
        </xsd:key>
        <xsd:key name="KurzusPrimaryKey">
            <xsd:selector xpath="Kurzusok/Kurzus"/>
            <xsd:field xpath="@KurzusID"/>
        </xsd:key>
        <xsd:key name="TanarPrimaryKey">
            <xsd:selector xpath="Tanarok/Tanar"/>
            <xsd:field xpath="@TanarID"/>
        </xsd:key>
        <xsd:key name="TantargyPrimaryKey">
            <xsd:selector xpath="Tantargyak/Tantargy"/>
            <xsd:field xpath="@TargyID"/>
        </xsd:key>
        <xsd:key name="TeremPrimaryKey">
            <xsd:selector xpath="Termek/Terem"/>
            <xsd:field xpath="@TeremID"/>
        </xsd:key>
        <xsd:keyref name="DiakKapcsolatRef" refer="DiakPrimaryKey">
            <xsd:selector xpath="Kapcsolatok/DiakKurzusKapcsolatok/Kapcsolat"/>
            <xsd:field xpath="@DiakID"/>
        </xsd:keyref>
        <xsd:keyref name="KurzusKapcsolatRef" refer="KurzusPrimaryKey">
            <xsd:selector xpath="Kapcsolatok/DiakKurzusKapcsolatok/Kapcsolat"/>
            <xsd:field xpath="@KurzusID"/>
        </xsd:keyref>
    </xsd:element>
</xsd:schema>

=== varga22/HK74CEXML/XMLTaskHK74CE/ElsőFeladat/XML_HK74CE.xml
<?xml version="1.0" encoding="UTF-8"?>
<HK74CE_oktatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaHK74CE.xsd">
    <!-- Diákok -->
    <Diakok>
        <!-- Diák példány #1 -->
        <Diak>
            <DiakID>HK74CE</DiakID>
            <Nev>
                <Keresztnev>Bence</Keresztnev>
                <Vezeteknev>Varga</Vezeteknev>
            </Nev>
            <SzulDatum>2000-05-12</SzulDatum>
            <Email>varga.bence2000@gmail.com</Email>
            <Email>varga.bence@student.uni-miskolc.hu</Email>
            <Lakcim>
                <Varos>Tiszafüred</Varos>
                <Utca>Bán Zsigmond</Utca>
                <Hazszam>02</Hazszam>
            </Lakcim>
        </Diak>
        <!-- Diák példány #2 -->
        <Diak>
            <DiakID>AAA000</DiakID>
            <Nev>
                <Keresztnev>Anna</Keresztnev>
                <Vezeteknev>Nagy</Vezeteknev>
            </Nev>
            <SzulDatum>1999-08-22</SzulDatum>
            <Email>anna.nagy@example.com</Email>
            <Lakcim>
                <Varos>Szeged</Varos>
                <Utca>Kossuth tér</Utca>
                <Hazszam>5</Hazszam>
            </Lakcim>
        </Diak>
        <!-- Diák példány #3 -->
        <Diak>
            <DiakID>BBB000</DiakID>
            <Nev>
                <Keresztnev>Péter</Keresztnev>
                <Vezeteknev>Kis</Vezeteknev>
            </Nev>
            <SzulDatum>2001-11-03</SzulDatum>
            <Email>peter.kis@example.com</Email>
            <Email>peter.kis@student.uni-miskolc.hu</Email>
            <Lakcim>
                <Varos>Debrecen</Varos>
                <Utca>Nagy utca</Utca>
                <Hazszam>8</Hazszam>
            </Lakcim>
        </Diak>
    </Diakok>

    <!-- Tanárok -->
    <Tanarok>
        <!-- Tanár példány #1 -->
        <Tanar>
            <TanarID>101</TanarID>
            <Nev>
                <Keresztnev>Anna</Keresztnev>
                <Vezeteknev>Szabó</Vezeteknev>
            </Nev>
            <Beosztas>Docens</Beosztas>
            <Szakterulet>Informatika</Szakterulet>
        </Tanar>
        <!-- Tanár példány #2 -->
        <Tanar>
            <TanarID>102</TanarID>
            <Nev>
                <Keresztnev>Balázs</Keresztnev>
                <Vezeteknev>Fekete</Vezeteknev>
            </Nev>
            <Beosztas>Adjunktus</Beosztas>
            <Szakterulet>Matematika</Szakterulet>
        </Tanar>
        <!-- Tanár példány #3 -->
        <Tanar>
            <TanarID>103</TanarID>
            <Nev>
                <Keresztnev>Mária</Keresztnev>
                <Vezeteknev>Fehér</Vezeteknev>
            </Nev>
            <Beosztas>Oktató</Beosztas>
            <Szakterulet>Fizika</Szakterulet>
        </Tanar>
    </Tanarok>

    <!-- Tantárgyak -->
    <Tantargyak>
        <!-- Tantárgy példány #1 -->
        <Tantargy>
            <TargyID>MAT101</TargyID>
            <Nev>Matematika</Nev>
            <Kredit>5</Kredit>
            <Nyelv>Magyar</Nyelv>
            <Nyelv>Angol</Nyelv>
        </Tantargy>
        <!-- Tantárgy példány #2 -->
        <Tantargy>
            <TargyID>INF202</TargyID>
            <Nev>Informatika</Nev>
            <Kredit>6</Kredit>
            <Nyelv>Magyar</Nyelv>
        </Tantargy>
        <!-- Tantárgy példány #3 -->
        <Tantargy>
            <TargyID>FIZ303</TargyID>
            <Nev>Angol</Nev>
            <Kredit>4</Kredit>
            <Nyelv>Angol</Nyelv>
        </Tantargy>
    </Tantargyak>

    <!-- Termek -->
    <Termek>
        <!-- Terem példány #1 -->
        <Terem>
            <TeremID>101</TeremID>
            <Nev>Eloadoterem A</Nev>
            <Kapacitas>100</Kapacitas>
            <Felszereles>Projektor</Felszereles>
            <Felszereles>Tábla</Felszereles>
        </Terem>
        <!-- Terem példány #2 -->
        <Terem>
            <TeremID>102</TeremID>
            <Nev>Labor B</Nev>
            <Kapacitas>30</Kapacitas>
            <Felszereles>Számítógépek</Felszereles>
        </Terem>
        <!-- Terem példány #3 -->
        <Terem>
            <TeremID>103</TeremID>
            <Nev>Eloadoterem C</Nev>
            <Kapacitas>50</Kapacitas>
            <Felszereles>Tábla</Felszereles>
        </Terem>
    </Termek>

    <!-- Kurzusok -->
    <Kurzusok>
        <!-- Kurzus példány #1 -->
        <Kurzus>
            <KurzusID>KURZ001</KurzusID>
            <Idopont>2024.12.05.</Idopont>
            <Tipus>
                <Eloadas>true</Eloadas>
                <Gyakorlat>false</Gyakorlat>
            </Tipus>
            <Letszam>30</Letszam>
        </Kurzus>
        <!-- Kurzus példány #2 -->
        <Kurzus>
            <KurzusID>KURZ002</KurzusID>
            <Idopont>2024.12.06.</Idopont>
            <Tipus>
                <Eloadas>false</Eloadas>
                <Gyakorlat>true</Gyakorlat>
            </Tipus>
            <Letszam>25</Letszam>
        </Kurzus>
        <!-- Kurzus példány #3 -->
        <Kurzus>
            <KurzusID>KURZ003</KurzusID>
            <Idopont>2024.12.07.</Idopont>
            <Tipus>
                <Eloadas>true</Eloadas>
                <Gyakorlat>true</Gyakorlat>
            </Tipus>
            <Letszam>40</Letszam>
        </Kurzus>
    </Kurzusok>

    <!-- Kapcsolatok -->
    <Kapcsolatok>
        <!-- Diák-Kurzus kapcsolat -->
        <DiakKurzusKapcsolatok>
            <Kapcsolat>
                <DiakID>1</DiakID>
                <KurzusID>KURZ001</KurzusID>
                <Vizsga>90</Vizsga>
                <Alairas>aláírva</Alairas>
            </Kapcsolat>
            <Kapcsolat>
                <DiakID>2</DiakID>
                <KurzusID>KURZ002</KurzusID>
                <Vizsga>10</Vizsga>
                <Alairas>megtagadva</Alairas>
            </Kapcsolat>
            <Kapcsolat>
                <DiakID>3</DiakID>
                <KurzusID>KURZ003</KurzusID>
                <Vizsga>80</Vizsga>
                <Alairas>aláírva</Alairas>
            </Kapcsolat>
        </DiakKurzusKapcsolatok>

    </Kapcsolatok>
</HK74CE_oktatas>

=== varga22/HK74CEXML/XMLTaskHK74CE/MásodikFeladat/DOMParseHK74CE/XML_HK74CE1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<HK74CE_oktatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaHK74CE.xsd">
      
  <!-- Diákok -->
      
  <Diakok>
            
    <Diak DiakID="1">
                  
      <Nev>
                        
        <Keresztnev>Bence</Keresztnev>
                        
        <Vezeteknev>Varga</Vezeteknev>
                    
      </Nev>
                  
      <SzulDatum>2000-05-12</SzulDatum>
                  
      <Email>varga.bence2000@gmail.com</Email>
                  
      <Email>varga.bence@student.uni-miskolc.hu</Email>
                  
      <Lakcim>
                        
        <Varos>Tiszafüred</Varos>
                        
        <Utca>Bán Zsigmond</Utca>
                        
        <Hazszam>02</Hazszam>
                    
      </Lakcim>
              
    </Diak>
            
    <Diak DiakID="2">
                  
      <Nev>
                        
        <Keresztnev>Anna</Keresztnev>
                        
        <Vezeteknev>Nagy</Vezeteknev>
                    
      </Nev>
                  
      <SzulDatum>1999-08-22</SzulDatum>
                  
      <Email>anna.nagy@example.com</Email>
                  
      <Email>anna.student@example.com</Email>
                  
      <Email>anna.office@example.hu</Email>
                  
      <Lakcim>
                        
        <Varos>Szeged</Varos>
                        
        <Utca>Kossuth tér</Utca>
                        
        <Hazszam>5</Hazszam>
                    
      </Lakcim>
              
    </Diak>
            
    <Diak DiakID="3">
                  
      <Nev>
                        
        <Keresztnev>Péter</Keresztnev>
                        
        <Vezeteknev>Kis</Vezeteknev>
                    
      </Nev>
                  
      <SzulDatum>2001-11-03</SzulDatum>
                  
      <Email>peter.kis@example.com</Email>
                  
      <Email>peter.kis@student.uni-miskolc.hu</Email>
                  
      <Lakcim>
                        
        <Varos>Debrecen</Varos>
                        
        <Utca>Nagy utca</Utca>
                        
        <Hazszam>8</Hazszam>
                    
      </Lakcim>
              
    </Diak>
        
  </Diakok>
      
  <!-- Tanárok -->
      
  <Tanarok>
            
    <Tanar TanarID="101">
                  
      <Nev>
                        
        <Keresztnev>Anna</Keresztnev>
                        
        <Vezeteknev>Szabó</Vezeteknev>
                    
      </Nev>
                  
      <Beosztas>Docens</Beosztas>
                  
      <Szakterulet>Informatika</Szakterulet>
              
    </Tanar>
            
    <Tanar TanarID="102">
                  
      <Nev>
                        
        <Keresztnev>Balázs</Keresztnev>
                        
        <Vezeteknev>Fekete</Vezeteknev>
                    
      </Nev>
                  
      <Beosztas>Adjunktus</Beosztas>
                  
      <Szakterulet>Matematika</Szakterulet>
              
    </Tanar>
            
    <Tanar TanarID="103">
                  
      <Nev>
                        
        <Keresztnev>Mária</Keresztnev>
                        
        <Vezeteknev>Fehér</Vezeteknev>
                    
      </Nev>
                  
      <Beosztas>Oktató</Beosztas>
                  
      <Szakterulet>Fizika</Szakterulet>
              
    </Tanar>
        
  </Tanarok>
      
  <!-- Tantárgyak -->
      
  <Tantargyak>
            
    <Tantargy TargyID="MAT101">
                  
      <Nev>Matematika</Nev>
                  
      <Kredit>5</Kredit>
                  
      <Nyelv>Magyar</Nyelv>
                  
      <Nyelv>Angol</Nyelv>
              
    </Tantargy>
            
    <Tantargy TargyID="INF202">
                  
      <Nev>Informatika</Nev>
                  
      <Kredit>5</Kredit>
                  
      <Nyelv>Magyar</Nyelv>
              
    </Tantargy>
            
    <Tantargy TargyID="FIZ303">
                  
      <Nev>Fizika</Nev>
                  
      <Kredit>4</Kredit>
                  
      <Nyelv>Angol</Nyelv>
              
    </Tantargy>
        
  </Tantargyak>
      
  <!-- Termek -->
      
  <Termek>
            
    <Terem TeremID="101">
                  
      <Nev>Eloadoterem A</Nev>
                  
      <Kapacitas>100</Kapacitas>
                  
      <Felszereles>Projektor</Felszereles>
                  
      <Felszereles>Tábla</Felszereles>
                  
      <Felszereles>Függöny</Felszereles>
              
    </Terem>
            
    <Terem TeremID="102">
                  
      <Nev>Labor B</Nev>
                  
      <Kapacitas>30</Kapacitas>
                  
      <Felszereles>Számítógépek</Felszereles>
              
    </Terem>
            
    <Terem TeremID="103">
                  
      <Nev>Eloadoterem C</Nev>
                  
      <Kapacitas>50</Kapacitas>
                  
      <Felszereles>Tábla</Felszereles>
              
    </Terem>
        
  </Termek>
      
  <!-- Kurzusok -->
      
  <Kurzusok>
            
    <Kurzus KurzusID="KURZ001">
                  
      <Idopont>2024-12-05</Idopont>
                  
      <Tipus>
                        
        <Eloadas>true</Eloadas>
                        
        <Gyakorlat>false</Gyakorlat>
                    
      </Tipus>
                  
      <Letszam>30</Letszam>
              
    </Kurzus>
            
    <Kurzus KurzusID="KURZ002">
                  
      <Idopont>2024-12-06</Idopont>
                  
      <Tipus>
                        
        <Eloadas>false</Eloadas>
                        
        <Gyakorlat>true</Gyakorlat>
                    
      </Tipus>
                  
      <Letszam>25</Letszam>
              
    </Kurzus>
            
    <Kurzus KurzusID="KURZ003">
                  
      <Idopont>2024-12-07</Idopont>
                  
      <Tipus>
                        
        <Eloadas>true</Eloadas>
                        
        <Gyakorlat>true</Gyakorlat>
                    
      </Tipus>
                  
      <Letszam>40</Letszam>
              
    </Kurzus>
        
  </Kurzusok>
      
  <!-- Kapcsolatok -->
      
  <Kapcsolatok>
            
    <DiakKurzusKapcsolatok>
                  
      <Kapcsolat DiakID="1" KurzusID="KURZ001">
                        
        <Vizsga>90</Vizsga>
                        
        <Alairas>aláírva</Alairas>
                    
      </Kapcsolat>
                  
      <Kapcsolat DiakID="2" KurzusID="KURZ002">
                        
        <Vizsga>10</Vizsga>
                        
        <Alairas>megtagadva</Alairas>
                    
      </Kapcsolat>
                  
      <Kapcsolat DiakID="3" KurzusID="KURZ003">
                        
        <Vizsga>80</Vizsga>
                        
        <Alairas>aláírva</Alairas>
                    
      </Kapcsolat>
              
    </DiakKurzusKapcsolatok>
        
  </Kapcsolatok>
  
</HK74CE_oktatas>
